### ISSUE TITLE
acc, s_cost and u_cost calculation

### ISSUE THREAD

**Issue by pribadihcr** [RobRomijnders/ladder#3]
Hi @RobRomijnders ,

Why the calculation of acc, s_cost and u_cost in training come with these formula?
acc_ma = 0.8*acc_ma+0.2*result[1]
 s_cost_ma = 0.8*s_cost_ma+0.2*result[2]
 u_cost_ma = 0.8*u_cost_ma+0.2*result[3]

**Comment by RobRomijnders** [comment]
the postfix _ma is to indicate a moving average
